import { getLlamaSummary } from './prompt.js';

chrome.runtime.onInstalled.addListener((details) => {
  if (details.reason === "install") {
    chrome.runtime.openOptionsPage();
  }
});

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === "openOptions") {
    chrome.runtime.openOptionsPage();
    return;
  }
  if (request.type === "summarizeContent") {
    // Receive the summary generated by Meta Llama and display in console. If the 
    // summary generation fails, display the error in console and return error response.
    (async () => {
      try {
        console.log("Received summarization request");
        const mode = request.summaryMode === "voice" ? "voice" : "text";
        const { summary, narration } = await getLlamaSummary(
          request.content,
          request.apiKey,
          mode
        );
        sendResponse({ success: true, summary, narration });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error("Summarization failed:", message);
        sendResponse({ success: false, summary: null, error: message });
      }
    })();

    // Return true to indicate we will respond asynchronously
    return true;
  }

  if (request.type === "openPopupPage") {
    chrome.tabs.create({
      url: chrome.runtime.getURL("popup.html")
    });
  }
});