import { getLlamaSummary } from './prompt.js';

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === "summarizeContent") {
    // Receive the summary generated by Meta Llama and display in console. If the 
    // summary generation fails, display the error in console and return error response.
    (async () => {
      try {
        console.log("Received summarization request");
        const summary = await getLlamaSummary(request.content);
        sendResponse({ success: true, summary });
      } catch (error) {
        //console.error("Error during summarization:", error);
        // sendResponse({ 
        //   success: false, 
        //   summary: "Error during summarization: " + error.message 
        // });
        sendResponse({ summary: null });
      }
    })();

    // Return true to indicate we will respond asynchronously
    return true;
  }

  if (request.type === "openPopupPage") {
    chrome.tabs.create({
      url: chrome.runtime.getURL("popup.html")
    });
  }
});