import { getLlamaSummary } from './prompt.js';

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === "summarizeContent") {
    // Receive the summary generated by Meta Llama and display in console. If the 
    // summary generation fails, display the error in console and return error response.
    (async () => {
      try {
        console.log("Received summarization request");
        const summary = await getLlamaSummary(request.content);
        console.log("Summary generated:", summary);
        sendResponse({ success: true, summary });
      } catch (error) {
        console.error("Error during summarization:", error);
        sendResponse({ 
          success: false, 
          summary: "Error during summarization: " + error.message 
        });
      }
    })();
    
    // Return true to indicate we will respond asynchronously
    return true;
  }
});